(ns msprandom.core-test
  (:require [clojure.test :refer :all]
            [msprandom.core :refer :all]
            [msprandom.crypto :as c]))

;;uncomment following lines to run tests  with human input
;;Warning! Run these tests in console only!

;(deftest kbdgenerator-test
;  (testing "human input random generator."
;    (let [b (msprandom.kbd/kbdrand 5)
;          _ (println "\ngenerated byte array:"(vec b))]
;      (is (not= nil b)))))
;

;(deftest new-vault-test
;  (testing "Test new vault."
;    (let [rand-data (new-vault "vault.edn" "Secret12")]
;      (is (not= nil rand-data))
;      (when rand-data
;        (println "saved random data: " (c/bytes-to-hex rand-data))))))
;
;(deftest load-vault-test
;  (testing "Test load vault."
;    (let [rand-data (load-vault "vault.edn" "Secret12")]
;      (when rand-data
;        (println "loaded random data:" (c/bytes-to-hex rand-data))))))
;
;(deftest load2-vault-test
;  (testing "Test load vault after update."
;    (let [rand-data (load-vault "vault.edn" "Secret12")]
;      (when rand-data
;        (println "loaded2 random data:" (c/bytes-to-hex rand-data))))))
;
;(deftest wrong-load-vault-test
;  (testing "Test load vault with wrong password."
;    (is (thrown? Exception (load-vault "vault.edn" "wrongPassword")))))

